import React, { useState, useEffect } from 'react';
import { Save, Loader2 } from 'lucide-react';
import { Button } from './ui/Button';

const API_URL = "http://localhost:8000/api";

export const NoteTaker: React.FC<{ topicId: string }> = ({ topicId }) => {
    const [note, setNote] = useState("");
    const [savedNotes, setSavedNotes] = useState<any[]>([]);
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        fetchNotes();
    }, [topicId]);

    const fetchNotes = async () => {
        const studentId = localStorage.getItem('student_id') || 'demo_student_123';
        try {
            const res = await fetch(`${API_URL}/notes/${studentId}/${topicId}`);
            const data = await res.json();
            if (Array.isArray(data)) {
                setSavedNotes(data);
            } else {
                setSavedNotes([]);
            }
        } catch (e) {
            console.error(e);
        }
    };

    const handleSave = async () => {
        if (!note.trim()) return;
        setSaving(true);
        const studentId = localStorage.getItem('student_id') || 'demo_student_123';

        try {
            await fetch(`${API_URL}/notes`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    id: "", // generated by backend
                    student_id: studentId,
                    topic_id: topicId,
                    content: note,
                    timestamp: new Date().toISOString()
                })
            });
            setNote("");
            fetchNotes();
        } catch (e) {
            console.error(e);
        } finally {
            setSaving(false);
        }
    };

    return (
        <div className="bg-yellow-50 border-2 border-black rounded-xl p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h3 className="font-black text-brand-black mb-2 flex items-center gap-2">
                📒 Field Notes: {topicId}
            </h3>

            <div className="max-h-32 overflow-y-auto mb-4 space-y-2">
                {savedNotes.map((n) => (
                    <div key={n.id} className="bg-white p-2 rounded border border-yellow-200 text-sm font-handwriting">
                        {n.content}
                    </div>
                ))}
                {savedNotes.length === 0 && <p className="text-sm text-gray-400 italic">No notes yet.</p>}
            </div>

            <div className="flex gap-2">
                <input
                    className="flex-1 border-2 border-black rounded px-2 py-1 text-sm focus:outline-none"
                    placeholder="Jot down a thought..."
                    value={note}
                    onChange={e => setNote(e.target.value)}
                    onKeyDown={e => e.key === 'Enter' && handleSave()}
                />
                <Button size="sm" onClick={handleSave} disabled={saving}>
                    {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                </Button>
            </div>
        </div>
    );
};
